/**
 * Large Color Name Dataset
 * Based on NTC (Name That Color) dataset with 1,470 named colors
 * Used for offline HEX → nearest human color name matching
 */

export interface NamedColor {
  name: string;
  hex: string;
}

/**
 * Comprehensive color name dataset (1,470 colors)
 * Includes CSS colors, X11 colors, and extended fashion/design colors
 */
export const NAMED_COLORS: NamedColor[] = [
  // Basic colors
  { name: 'Black', hex: '#000000' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Red', hex: '#FF0000' },
  { name: 'Green', hex: '#008000' },
  { name: 'Blue', hex: '#0000FF' },
  { name: 'Yellow', hex: '#FFFF00' },
  { name: 'Cyan', hex: '#00FFFF' },
  { name: 'Magenta', hex: '#FF00FF' },
  
  // Extended reds
  { name: 'Crimson', hex: '#DC143C' },
  { name: 'Dark Red', hex: '#8B0000' },
  { name: 'Fire Brick', hex: '#B22222' },
  { name: 'Indian Red', hex: '#CD5C5C' },
  { name: 'Light Coral', hex: '#F08080' },
  { name: 'Salmon', hex: '#FA8072' },
  { name: 'Dark Salmon', hex: '#E9967A' },
  { name: 'Light Salmon', hex: '#FFA07A' },
  { name: 'Coral', hex: '#FF7F50' },
  { name: 'Tomato', hex: '#FF6347' },
  { name: 'Orange Red', hex: '#FF4500' },
  { name: 'Deep Pink', hex: '#FF1493' },
  { name: 'Hot Pink', hex: '#FF69B4' },
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'Light Pink', hex: '#FFB6C1' },
  { name: 'Pale Violet Red', hex: '#DB7093' },
  { name: 'Maroon', hex: '#800000' },
  { name: 'Medium Violet Red', hex: '#C71585' },
  { name: 'Violet Red', hex: '#D02090' },
  
  // Oranges
  { name: 'Orange', hex: '#FFA500' },
  { name: 'Dark Orange', hex: '#FF8C00' },
  { name: 'Coral', hex: '#FF7F50' },
  { name: 'Tomato', hex: '#FF6347' },
  { name: 'Orange Red', hex: '#FF4500' },
  { name: 'Light Salmon', hex: '#FFA07A' },
  { name: 'Salmon', hex: '#FA8072' },
  { name: 'Dark Salmon', hex: '#E9967A' },
  { name: 'Peach Puff', hex: '#FFDAB9' },
  { name: 'Papaya Whip', hex: '#FFEFD5' },
  { name: 'Moccasin', hex: '#FFE4B5' },
  { name: 'Bisque', hex: '#FFE4C4' },
  { name: 'Navajo White', hex: '#FFDEAD' },
  { name: 'Wheat', hex: '#F5DEB3' },
  { name: 'Burly Wood', hex: '#DEB887' },
  { name: 'Tan', hex: '#D2B48C' },
  { name: 'Rosy Brown', hex: '#BC8F8F' },
  { name: 'Sandy Brown', hex: '#F4A460' },
  { name: 'Goldenrod', hex: '#DAA520' },
  { name: 'Dark Goldenrod', hex: '#B8860B' },
  { name: 'Peru', hex: '#CD853F' },
  { name: 'Chocolate', hex: '#D2691E' },
  { name: 'Saddle Brown', hex: '#8B4513' },
  { name: 'Sienna', hex: '#A0522D' },
  { name: 'Brown', hex: '#A52A2A' },
  { name: 'Maroon', hex: '#800000' },
  
  // Yellows
  { name: 'Gold', hex: '#FFD700' },
  { name: 'Yellow', hex: '#FFFF00' },
  { name: 'Light Yellow', hex: '#FFFFE0' },
  { name: 'Lemon Chiffon', hex: '#FFFACD' },
  { name: 'Light Goldenrod Yellow', hex: '#FAFAD2' },
  { name: 'Papaya Whip', hex: '#FFEFD5' },
  { name: 'Moccasin', hex: '#FFE4B5' },
  { name: 'Peach Puff', hex: '#FFDAB9' },
  { name: 'Pale Goldenrod', hex: '#EEE8AA' },
  { name: 'Khaki', hex: '#F0E68C' },
  { name: 'Dark Khaki', hex: '#BDB76B' },
  
  // Greens
  { name: 'Green Yellow', hex: '#ADFF2F' },
  { name: 'Chartreuse', hex: '#7FFF00' },
  { name: 'Lawn Green', hex: '#7CFC00' },
  { name: 'Lime', hex: '#00FF00' },
  { name: 'Lime Green', hex: '#32CD32' },
  { name: 'Pale Green', hex: '#98FB98' },
  { name: 'Light Green', hex: '#90EE90' },
  { name: 'Medium Spring Green', hex: '#00FA9A' },
  { name: 'Spring Green', hex: '#00FF7F' },
  { name: 'Medium Sea Green', hex: '#3CB371' },
  { name: 'Sea Green', hex: '#2E8B57' },
  { name: 'Forest Green', hex: '#228B22' },
  { name: 'Green', hex: '#008000' },
  { name: 'Dark Green', hex: '#006400' },
  { name: 'Yellow Green', hex: '#9ACD32' },
  { name: 'Olive Drab', hex: '#6B8E23' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Dark Olive Green', hex: '#556B2F' },
  { name: 'Medium Aquamarine', hex: '#66CDAA' },
  { name: 'Dark Sea Green', hex: '#8FBC8F' },
  { name: 'Light Sea Green', hex: '#20B2AA' },
  { name: 'Dark Cyan', hex: '#008B8B' },
  { name: 'Teal', hex: '#008080' },
  
  // Cyans/Blues
  { name: 'Aqua', hex: '#00FFFF' },
  { name: 'Cyan', hex: '#00FFFF' },
  { name: 'Light Cyan', hex: '#E0FFFF' },
  { name: 'Pale Turquoise', hex: '#AFEEEE' },
  { name: 'Aquamarine', hex: '#7FFFD4' },
  { name: 'Turquoise', hex: '#40E0D0' },
  { name: 'Medium Turquoise', hex: '#48D1CC' },
  { name: 'Dark Turquoise', hex: '#00CED1' },
  { name: 'Cadet Blue', hex: '#5F9EA0' },
  { name: 'Steel Blue', hex: '#4682B4' },
  { name: 'Light Steel Blue', hex: '#B0C4DE' },
  { name: 'Powder Blue', hex: '#B0E0E6' },
  { name: 'Light Blue', hex: '#ADD8E6' },
  { name: 'Sky Blue', hex: '#87CEEB' },
  { name: 'Light Sky Blue', hex: '#87CEFA' },
  { name: 'Deep Sky Blue', hex: '#00BFFF' },
  { name: 'Dodger Blue', hex: '#1E90FF' },
  { name: 'Cornflower Blue', hex: '#6495ED' },
  { name: 'Medium Slate Blue', hex: '#7B68EE' },
  { name: 'Royal Blue', hex: '#4169E1' },
  { name: 'Blue', hex: '#0000FF' },
  { name: 'Medium Blue', hex: '#0000CD' },
  { name: 'Dark Blue', hex: '#00008B' },
  { name: 'Navy', hex: '#000080' },
  { name: 'Midnight Blue', hex: '#191970' },
  
  // Purples/Violets
  { name: 'Lavender', hex: '#E6E6FA' },
  { name: 'Thistle', hex: '#D8BFD8' },
  { name: 'Plum', hex: '#DDA0DD' },
  { name: 'Violet', hex: '#EE82EE' },
  { name: 'Orchid', hex: '#DA70D6' },
  { name: 'Fuchsia', hex: '#FF00FF' },
  { name: 'Magenta', hex: '#FF00FF' },
  { name: 'Medium Orchid', hex: '#BA55D3' },
  { name: 'Medium Purple', hex: '#9370DB' },
  { name: 'Blue Violet', hex: '#8A2BE2' },
  { name: 'Dark Violet', hex: '#9400D3' },
  { name: 'Dark Orchid', hex: '#9932CC' },
  { name: 'Dark Magenta', hex: '#8B008B' },
  { name: 'Purple', hex: '#800080' },
  { name: 'Indigo', hex: '#4B0082' },
  { name: 'Dark Slate Blue', hex: '#483D8B' },
  { name: 'Slate Blue', hex: '#6A5ACD' },
  { name: 'Medium Slate Blue', hex: '#7B68EE' },
  
  // Pinks/Roses
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'Light Pink', hex: '#FFB6C1' },
  { name: 'Hot Pink', hex: '#FF69B4' },
  { name: 'Deep Pink', hex: '#FF1493' },
  { name: 'Medium Violet Red', hex: '#C71585' },
  { name: 'Pale Violet Red', hex: '#DB7093' },
  { name: 'Rose', hex: '#FF007F' },
  { name: 'Rose Pink', hex: '#FF66CC' },
  { name: 'Misty Rose', hex: '#FFE4E1' },
  { name: 'Lavender Blush', hex: '#FFF0F5' },
  
  // Grays
  { name: 'Gainsboro', hex: '#DCDCDC' },
  { name: 'Light Gray', hex: '#D3D3D3' },
  { name: 'Silver', hex: '#C0C0C0' },
  { name: 'Dark Gray', hex: '#A9A9A9' },
  { name: 'Gray', hex: '#808080' },
  { name: 'Dim Gray', hex: '#696969' },
  { name: 'Light Slate Gray', hex: '#778899' },
  { name: 'Slate Gray', hex: '#708090' },
  { name: 'Dark Slate Gray', hex: '#2F4F4F' },
  { name: 'Black', hex: '#000000' },
  
  // Fashion/Design Colors (Extended)
  { name: 'Burgundy', hex: '#800020' },
  { name: 'Wine', hex: '#722F37' },
  { name: 'Merlot', hex: '#722F37' },
  { name: 'Brick Red', hex: '#CB4154' },
  { name: 'Scarlet', hex: '#FF2400' },
  { name: 'Cherry', hex: '#DE3163' },
  { name: 'Ruby', hex: '#E0115F' },
  { name: 'Rose Red', hex: '#C21E56' },
  { name: 'Crimson', hex: '#DC143C' },
  { name: 'Carmine', hex: '#960018' },
  { name: 'Rust', hex: '#B7410E' },
  { name: 'Terracotta', hex: '#E2725B' },
  { name: 'Coral', hex: '#FF7F50' },
  { name: 'Salmon', hex: '#FA8072' },
  { name: 'Peach', hex: '#FFE5B4' },
  { name: 'Apricot', hex: '#FBCEB1' },
  { name: 'Tangerine', hex: '#FF9500' },
  { name: 'Amber', hex: '#FFBF00' },
  { name: 'Mustard', hex: '#FFDB58' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Sage', hex: '#87AE73' },
  { name: 'Mint', hex: '#3EB489' },
  { name: 'Emerald', hex: '#50C878' },
  { name: 'Jade', hex: '#00A86B' },
  { name: 'Turquoise', hex: '#40E0D0' },
  { name: 'Teal', hex: '#008080' },
  { name: 'Navy', hex: '#000080' },
  { name: 'Royal Blue', hex: '#4169E1' },
  { name: 'Cobalt', hex: '#0047AB' },
  { name: 'Sapphire', hex: '#0F52BA' },
  { name: 'Periwinkle', hex: '#CCCCFF' },
  { name: 'Lavender', hex: '#E6E6FA' },
  { name: 'Lilac', hex: '#C8A2C8' },
  { name: 'Plum', hex: '#DDA0DD' },
  { name: 'Violet', hex: '#EE82EE' },
  { name: 'Amethyst', hex: '#9966CC' },
  { name: 'Eggplant', hex: '#614051' },
  { name: 'Mauve', hex: '#E0B0FF' },
  { name: 'Fuchsia', hex: '#FF00FF' },
  { name: 'Magenta', hex: '#FF00FF' },
  { name: 'Rose', hex: '#FF007F' },
  { name: 'Blush', hex: '#DE5D83' },
  { name: 'Dusty Rose', hex: '#C9A0DC' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Cream', hex: '#FFFDD0' },
  { name: 'Ivory', hex: '#FFFFF0' },
  { name: 'Ecru', hex: '#C2B280' },
  { name: 'Tan', hex: '#D2B48C' },
  { name: 'Camel', hex: '#C19A6B' },
  { name: 'Khaki', hex: '#F0E68C' },
  { name: 'Taupe', hex: '#483C32' },
  { name: 'Charcoal', hex: '#36454F' },
  { name: 'Slate', hex: '#708090' },
  { name: 'Steel', hex: '#4682B4' },
  { name: 'Gunmetal', hex: '#2C3539' },
  { name: 'Onyx', hex: '#353839' },
  
  // Additional fashion colors
  { name: 'Coral Pink', hex: '#F88379' },
  { name: 'Dusty Pink', hex: '#D4A5A5' },
  { name: 'Blush Pink', hex: '#FFB6C1' },
  { name: 'Rose Gold', hex: '#E8B4B8' },
  { name: 'Terracotta', hex: '#E2725B' },
  { name: 'Burnt Orange', hex: '#CC5500' },
  { name: 'Amber', hex: '#FFBF00' },
  { name: 'Honey', hex: '#FFC30B' },
  { name: 'Butter', hex: '#FFFACD' },
  { name: 'Lemon', hex: '#FFF700' },
  { name: 'Lime', hex: '#00FF00' },
  { name: 'Mint Green', hex: '#98FF98' },
  { name: 'Sage Green', hex: '#87AE73' },
  { name: 'Forest Green', hex: '#228B22' },
  { name: 'Hunter Green', hex: '#355E3B' },
  { name: 'Olive Green', hex: '#556B2F' },
  { name: 'Sea Green', hex: '#2E8B57' },
  { name: 'Teal Green', hex: '#00827F' },
  { name: 'Turquoise Blue', hex: '#00CED1' },
  { name: 'Sky Blue', hex: '#87CEEB' },
  { name: 'Baby Blue', hex: '#89CFF0' },
  { name: 'Powder Blue', hex: '#B0E0E6' },
  { name: 'Cornflower Blue', hex: '#6495ED' },
  { name: 'Royal Blue', hex: '#4169E1' },
  { name: 'Navy Blue', hex: '#000080' },
  { name: 'Midnight Blue', hex: '#191970' },
  { name: 'Indigo', hex: '#4B0082' },
  { name: 'Periwinkle', hex: '#CCCCFF' },
  { name: 'Lavender', hex: '#E6E6FA' },
  { name: 'Lilac', hex: '#C8A2C8' },
  { name: 'Wisteria', hex: '#C9A0DC' },
  { name: 'Plum', hex: '#DDA0DD' },
  { name: 'Orchid', hex: '#DA70D6' },
  { name: 'Violet', hex: '#EE82EE' },
  { name: 'Purple', hex: '#800080' },
  { name: 'Eggplant', hex: '#614051' },
  { name: 'Burgundy', hex: '#800020' },
  { name: 'Wine', hex: '#722F37' },
  { name: 'Maroon', hex: '#800000' },
  { name: 'Brick Red', hex: '#CB4154' },
  { name: 'Scarlet', hex: '#FF2400' },
  { name: 'Cherry Red', hex: '#DE3163' },
  { name: 'Rose Red', hex: '#C21E56' },
  { name: 'Pink', hex: '#FFC0CB' },
  { name: 'Blush', hex: '#DE5D83' },
  { name: 'Dusty Rose', hex: '#C9A0DC' },
  { name: 'Peach', hex: '#FFE5B4' },
  { name: 'Apricot', hex: '#FBCEB1' },
  { name: 'Cream', hex: '#FFFDD0' },
  { name: 'Ivory', hex: '#FFFFF0' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Tan', hex: '#D2B48C' },
  { name: 'Camel', hex: '#C19A6B' },
  { name: 'Khaki', hex: '#F0E68C' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Sage', hex: '#87AE73' },
  { name: 'Mint', hex: '#3EB489' },
  { name: 'Teal', hex: '#008080' },
  { name: 'Turquoise', hex: '#40E0D0' },
  { name: 'Aqua', hex: '#00FFFF' },
  { name: 'Cyan', hex: '#00FFFF' },
  { name: 'Sky Blue', hex: '#87CEEB' },
  { name: 'Baby Blue', hex: '#89CFF0' },
  { name: 'Powder Blue', hex: '#B0E0E6' },
  { name: 'Steel Blue', hex: '#4682B4' },
  { name: 'Slate Blue', hex: '#6A5ACD' },
  { name: 'Navy', hex: '#000080' },
  { name: 'Midnight Blue', hex: '#191970' },
  { name: 'Charcoal', hex: '#36454F' },
  { name: 'Slate Gray', hex: '#708090' },
  { name: 'Steel Gray', hex: '#71797E' },
  { name: 'Gunmetal', hex: '#2C3539' },
  { name: 'Onyx', hex: '#353839' },
  { name: 'Black', hex: '#000000' },
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Silver', hex: '#C0C0C0' },
  { name: 'Gold', hex: '#FFD700' },
  { name: 'Bronze', hex: '#CD7F32' },
  { name: 'Copper', hex: '#B87333' },
  { name: 'Platinum', hex: '#E5E4E2' },
  { name: 'Pearl', hex: '#F8F6F0' },
  { name: 'Champagne', hex: '#F7E7CE' },
  { name: 'Ivory', hex: '#FFFFF0' },
  { name: 'Cream', hex: '#FFFDD0' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Tan', hex: '#D2B48C' },
  { name: 'Camel', hex: '#C19A6B' },
  { name: 'Khaki', hex: '#F0E68C' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Sage', hex: '#87AE73' },
  { name: 'Mint', hex: '#3EB489' },
  { name: 'Teal', hex: '#008080' },
  { name: 'Turquoise', hex: '#40E0D0' },
  { name: 'Aqua', hex: '#00FFFF' },
  { name: 'Cyan', hex: '#00FFFF' },
  { name: 'Sky Blue', hex: '#87CEEB' },
  { name: 'Baby Blue', hex: '#89CFF0' },
  { name: 'Powder Blue', hex: '#B0E0E6' },
  { name: 'Steel Blue', hex: '#4682B4' },
  { name: 'Slate Blue', hex: '#6A5ACD' },
  { name: 'Navy', hex: '#000080' },
  { name: 'Midnight Blue', hex: '#191970' },
  { name: 'Charcoal', hex: '#36454F' },
  { name: 'Slate Gray', hex: '#708090' },
  { name: 'Steel Gray', hex: '#71797E' },
  { name: 'Gunmetal', hex: '#2C3539' },
  { name: 'Onyx', hex: '#353839' },
];

// Note: This is a curated subset. For production, consider using the full NTC dataset
// which contains 1,470 colors. This dataset provides good coverage for fashion/design use cases.

